FROM bitnami/node:18 as builder

WORKDIR /app/
ADD . /app/
RUN npm cache clean --force
RUN npm config get registry

ENV NODE_OPTIONS=--max-old-space-size=8000
ENV NODE_OPTIONS=--max_old_space_size=8000

RUN npm install
RUN npm build:ssr:Umbralf

EXPOSE 4000/tcp

CMD ["npm", "serve:ssr:Umbralf"]