// eslint-disable-next-line
module.exports = {
  listNames: [
    'VeoVeo',
    'Umbralf',
    'Supermax',
    'Acubamos',
    'GranComercial',
    'Marlin',
    'MiBulevar-Etecsa',
    'Pruebalo',
    'Apululu',
    // 'GranComerial-Mayoristas',
    // 'Mercado+',
    // 'MiBulevar-Genesis',
    // 'PymesBulevar',
    // 'Atec',
    // 'GranFerretero',
    // 'MercadosPresidente',
    // 'MiBulevar-Gesin',
    // 'RapidMultiservice',
    // 'Bianca',
    // 'HavTel',
    // 'MiBulevar',
    // 'MiBulevar-Mercatuaba',
    // 'Caracol',
    // 'HomeDeli',
    // 'MiBulevar-Alcansan',
    // 'MiBulevar-Ofa',
    // 'DCero',
    // 'ITH',
    // 'MiBulevar-Aligan ',
    // 'MiBulevar-TiendasPatrimonio',
    // 'Donato',
    // 'LaCeiba',
    // 'MiBulevar-ComercioCienfueg',
    // 'MiBulevar-Trd',
    // 'DondeDorian',
    // 'LaLuciana',
    // 'MiBulevar-Constelaciones',
    // 'MisterDamian',
    // 'Dujo',
    // 'LaPolimita',
    // 'MiBulevar-Cupetcfg',
    // 'MundoCopextel',
    // 'ElAjibe',
    // 'LaTorre',
    // 'MiBulevar-Cupetgrm',
    // 'OpticasTheia',
    // 'ElGuajirito',
    // 'LasPraderas',
    // 'MiBulevar-Cupethol',
    // 'Palmares',
    // 'Ferretero',
    // 'MCV',
    // 'MiBulevar-Cupetltu',
    // 'Parranda',
    // 'Gelato',
    // 'MM_Caribe',
    // 'MiBulevar-Epueblo',
    // 'PeopleGoTo',
  ],
};
